### ISSUE TITLE
cannot import name 'GPTNeoXForCausalLM' from 'transformers'

### ISSUE THREAD

**Issue by judyhappy** [mallorbc/Finetune_LLMs#17]
I followed the install_requirements.sh, but meet transformers error: 

   pip list:
   torch  2.0.0 
   transformers  4.14.1

```
finetuning_repo# deepspeed --num_gpus=4 run_clm.py --deepspeed ds_config_stage3.json --model_name_or_path decapoda-research/llama-7b-hf --train_file train.csv --validation_file validation.csv --do_train --do_eval --fp16 --overwrite_cache --evaluation_strategy=steps --output_dir finetuned --num_train_epochs 1  --eval_steps 20 --gradient_accumulation_steps 32 --per_device_train_batch_size 1 --use_fast_tokenizer False --learning_rate 5e-06 --warmup_steps 10 --save_total_limit 1 --save_steps 20 --save_strategy steps --load_best_model_at_end=True --block_size=176 --report_to=wandb
[2023-04-09 09:20:55,965] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-04-09 09:20:56,017] [INFO] [runner.py:550:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None run_clm.py --deepspeed ds_config_stage3.json --model_name_or_path decapoda-research/llama-7b-hf --train_file train.csv --validation_file validation.csv --do_train --do_eval --fp16 --overwrite_cache --evaluation_strategy=steps --output_dir finetuned --num_train_epochs 1 --eval_steps 20 --gradient_accumulation_steps 32 --per_device_train_batch_size 1 --use_fast_tokenizer False --learning_rate 5e-06 --warmup_steps 10 --save_total_limit 1 --save_steps 20 --save_strategy steps --load_best_model_at_end=True --block_size=176 --report_to=wandb
[2023-04-09 09:20:57,540] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2023-04-09 09:20:57,540] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=4, node_rank=0
[2023-04-09 09:20:57,540] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2023-04-09 09:20:57,540] [INFO] [launch.py:162:main] dist_world_size=4
[2023-04-09 09:20:57,541] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
Traceback (most recent call last):
  File "run_clm.py", line 51, in <module>
    from transformers import GPTNeoXForCausalLM, GPTNeoXTokenizerFast
ImportError: cannot import name 'GPTNeoXForCausalLM' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "run_clm.py", line 51, in <module>
    from transformers import GPTNeoXForCausalLM, GPTNeoXTokenizerFast
ImportError: cannot import name 'GPTNeoXForCausalLM' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "run_clm.py", line 51, in <module>
    from transformers import GPTNeoXForCausalLM, GPTNeoXTokenizerFast
ImportError: cannot import name 'GPTNeoXForCausalLM' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "run_clm.py", line 51, in <module>
    from transformers import GPTNeoXForCausalLM, GPTNeoXTokenizerFast
ImportError: cannot import name 'GPTNeoXForCausalLM' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/__init__.py)
```

I think it is due to transformers version, so i updated the transformers to 4.27.4, then this issue got fixed but there is another error:
```
Traceback (most recent call last):
  File "run_clm.py", line 548, in <module>
    main()
  File "run_clm.py", line 315, in main
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
Traceback (most recent call last):
  File "run_clm.py", line 548, in <module>
    main()
  File "run_clm.py", line 315, in main
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
Traceback (most recent call last):
  File "run_clm.py", line 548, in <module>
    main()
  File "run_clm.py", line 315, in main
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
[INFO|configuration_utils.py:668] 2023-04-09 10:32:46,645 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--decapoda-research--llama-7b-hf/snapshots/5f98eefcc80e437ef68d457ad7bf167c2c6a1348/config.json
Traceback (most recent call last):
  File "run_clm.py", line 548, in <module>
    main()
  File "run_clm.py", line 315, in main
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
```

**Comment by judyhappy** [comment]
With transformers 4.14.1 cannot import name 'GPTNeoXForCausalLM', with 4.27.4, KeyError: 'llama'.
Which version of transformers  should I use?

**Comment by judyhappy** [comment]
Fixed
