### ISSUE TITLE
Can't find a valid checkpoint 

### ISSUE THREAD

**Issue by judyhappy** [mallorbc/Finetune_LLMs#18]
Hi,

I downloaded all the files from https://huggingface.co/decapoda-research/llama-7b-hf/tree/main into  folder  /Finetune_LLMs/finetuning_repo/model/llama-7b-hf/, and tried to do fine-tune with command :

```
Finetune_LLMs/finetuning_repo# deepspeed --num_gpus=2 run_clm.py --deepspeed ds_config_stage3.json --model_name_or_path ./model/llama-7b-hf --train_file train.csv --validation_file validation.csv --do_train --do_eval --fp16 --overwrite_cache --evaluation_strategy=steps --output_dir finetuned --num_train_epochs 1  --eval_steps 20 --gradient_accumulation_steps 32 --per_device_train_batch_size 1 --use_fast_tokenizer False --learning_rate 5e-06 --warmup_steps 10 --save_total_limit 1 --save_steps 20 --save_strategy steps --load_best_model_at_end=True --block_size=176 --report_to=wandb
```

But I always get following error showing "Can't find a valid checkpoint at ./model/llama-7b-hf".
Where can I get this checkpoint?

```
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0003452301025390625 seconds
Traceback (most recent call last):
  File "run_clm.py", line 548, in <module>
    main()
  File "run_clm.py", line 511, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1628, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1697, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/usr/local/lib/python3.8/dist-packages/transformers/deepspeed.py", line 398, in deepspeed_init
    raise ValueError(f"Can't find a valid checkpoint at {resume_from_checkpoint}")
ValueError: Can't find a valid checkpoint at ./model/llama-7b-hf
```

**Comment by mallorbc** [comment]
Use the models on the huggingface hub or a local model
