### ISSUE TITLE
Can't perform example_run, getting an error after deepspeed is initialized

### ISSUE THREAD

**Issue by spupe** [mallorbc/Finetune_LLMs#2]
I am trying to run the repo on a fresh Ubuntu 20.04 install. My hardware is a 3090 with 128gb RAM. After I try the example_run string, the code runs fine until it activates DeepSpeed (ZeRO-3: activating zero.init() for this model) and starts loading up on RAM. When it gets to about 37gb, I get this error:

Traceback (most recent call last):
  File "run_clm.py", line 485, in <module>
    main()
  File "run_clm.py", line 330, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 419, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1452, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys, error_msgs = cls._load_state_dict_into_model(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1602, in _load_state_dict_into_model
    load(model_to_load, prefix=start_prefix)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1587, in load
    load(child, prefix + name + ".")
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1587, in load
    load(child, prefix + name + ".")
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1581, in load
    module._load_from_state_dict(*args)
  File "/home/spupe/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1327, in __exit__
    self.params[0].partition(param_list=self.params, has_been_updated=True)
  File "/home/spupe/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 605, in partition
    self._partition(param_list, has_been_updated=has_been_updated)
  File "/home/spupe/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 717, in _partition
    self._partition_param(param, has_been_updated=has_been_updated)
  File "/home/spupe/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 834, in _partition_param
    param.data = torch.ones(1, dtype=self.dtype).to(param.device)
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2021-12-06 10:12:10,624] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 45634
[2021-12-06 10:12:10,624] [ERROR] [launch.py:137:sigkill_handler] ['/usr/bin/python3', '-u', 'run_clm.py', '--local_rank=0', '--deepspeed', 'ds_config_gptj6b.json', '--model_name_or_path', 'EleutherAI/gpt-j-6B', '--train_file', 'train.csv', '--validation_file', 'validation.csv', '--do_train', '--do_eval', '--fp16', '--overwrite_cache', '--evaluation_strategy=steps', '--output_dir', 'finetuned', '--num_train_epochs', '12', '--eval_steps', '1', '--gradient_accumulation_steps', '32', '--per_device_train_batch_size', '1', '--use_fast_tokenizer', 'False', '--learning_rate', '5e-06', '--warmup_steps', '10', '--save_total_limit', '20', '--save_steps', '2', '--save_strategy', 'steps', '--tokenizer_name', 'gpt2'] exits with return code = 1

It seems to me this could be a CUDA error, but I can run the other repo (gpt-j-6B) with no issues, and I also tried reinstalling CUDA already. Any thoughts about what could be the problem here?

edit: by the way, I did try running CUDA_LAUNCH_BLOCKING=1 but that didn't produce any meaningful differences in the Traceback, the two sentences after RuntimeError were simply removed then

**Comment by spupe** [comment]
Hi, just an update here, I ended up doing a fresh Ubuntu 20.04 install where I manually downloaded and installed CUDA 11.1 from Nvidia, installed that without the drivers and then installed the 455 drivers with the command line (sudo apt install nvidia-driver-455) after disabling Nouveau and that worked. 

I don't think the error was related to this repo, so I'm closing the issue.

**Comment by mallorbc** [comment]
I know you can't have Nouveau and Nvidia drivers installed at the same time, so that likely was the issue.

Thanks for opening up an issue though!
