### ISSUE TITLE
deepspeed>=0.5.7 is required by recent versions of the transformers package

### ISSUE THREAD

**Issue by MihaiBalint** [mallorbc/Finetune_LLMs#3]
As of Dec. 15, the `install_requirements.sh` script will pull in transformers version 4.14.1 which no longer works with deepspeed 0.5.3, the following exception is raised when starting training with deepspeed:

```
[2021-12-15 20:34:58,064] [INFO] [runner.py:360:main] cmd = /home/mihai/anaconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 run_clm.py --deepspeed ds_config_gptj6b.json --model_name_or_path EleutherAI/gpt-j-6B --train_file train.csv --validation_file validation.csv --do_train --do_eval --fp16 --overwrite_cache --evaluation_strategy=steps --output_dir finetuned --num_train_epochs 12 --eval_steps 1 --gradient_accumulation_steps 32 --per_device_train_batch_size 1 --use_fast_tokenizer False --learning_rate 5e-06 --warmup_steps 10 --save_total_limit 20 --save_steps 10 --save_strategy steps --tokenizer_name gpt2
[2021-12-15 20:34:58,876] [INFO] [launch.py:80:main] WORLD INFO DICT: {'localhost': [0]}
[2021-12-15 20:34:58,876] [INFO] [launch.py:86:main] nnodes=1, num_local_procs=1, node_rank=0
[2021-12-15 20:34:58,876] [INFO] [launch.py:101:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2021-12-15 20:34:58,876] [INFO] [launch.py:102:main] dist_world_size=1
[2021-12-15 20:34:58,876] [INFO] [launch.py:104:main] Setting CUDA_VISIBLE_DEVICES=0
[2021-12-15 20:35:00,186] [INFO] [distributed.py:46:init_distributed] Initializing torch distributed with backend: nccl
Traceback (most recent call last):
  File "/home/mihai/workspace/tagarer-conda/finetuning_repo/run_clm.py", line 485, in <module>
    main()
  File "/home/mihai/workspace/tagarer-conda/finetuning_repo/run_clm.py", line 195, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/mihai/anaconda3/lib/python3.9/site-packages/transformers/hf_argparser.py", line 206, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 87, in __init__
  File "/home/mihai/anaconda3/lib/python3.9/site-packages/transformers/training_args.py", line 885, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/home/mihai/anaconda3/lib/python3.9/site-packages/transformers/deepspeed.py", line 173, in __init__
    super().__init__(config_file_or_dict)
  File "/home/mihai/anaconda3/lib/python3.9/site-packages/transformers/deepspeed.py", line 61, in __init__
    dep_version_check("deepspeed")
  File "/home/mihai/anaconda3/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 47, in dep_version_check
    require_version(deps[pkg], hint)
  File "/home/mihai/anaconda3/lib/python3.9/site-packages/transformers/utils/versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/home/mihai/anaconda3/lib/python3.9/site-packages/transformers/utils/versions.py", line 49, in _compare_versions
    raise ImportError(
ImportError: deepspeed>=0.5.7 is required for a normal functioning of this module, but found deepspeed==0.5.3+30537e7.
Killing subprocess 35522

```

**Comment by mallorbc** [comment]
I will fix this or you can make a pull request and I will review and accept it.  Thanks!

**Comment by MihaiBalint** [comment]
I've built the latest deepspeed (0.5.8) from source and it looks like it starts without error. I'll do a couple of finetuning rounds now and check if inference works ok on the checkpoints.

**Comment by MihaiBalint** [comment]
Looks like GPU memory use is lower with deepspeed 0.5.8 and there is about a 10% performance improvement in `eval/steps_per_second` and `eval/samples_per_second`. Nice.
